require 'rubygems'
require 'hpricot'
require 'open-uri'
require 'date'
require 'imdb/base'
require 'imdb/title'
require 'imdb/company'
require 'imdb/movie'
require 'imdb/name'
require 'imdb/genre'
require 'imdb/series'
require 'imdb/episode'

# For compatibility with the old skool way of doing things
require 'imdb/old_skool_compatibility'